// ============================================
// THE BIG BANG THEORY - Complete Show Database
// All Seasons, Episodes, Cast, Crew, Facts, Moments
// ============================================

const SHOW_INFO = {
  title: "The Big Bang Theory",
  tagline: "Our whole universe was in a hot, dense state...",
  network: "CBS",
  premiered: "September 24, 2007",
  ended: "May 16, 2019",
  seasons: 12,
  totalEpisodes: 279,
  creators: "Chuck Lorre & Bill Prady",
  genre: "Sitcom / Comedy",
  avgViewers: "18.99 million",
  awards: "56 wins & 216 nominations",
  emmys: 10,
  imdbRating: 8.2
};

// ── CAST DATA ──
const MAIN_CAST = [
  {
    id: "sheldon",
    character: "Dr. Sheldon Cooper",
    actor: "Jim Parsons",
    color: "#3B82F6",
    initials: "SC",
    role: "Theoretical Physicist",
    seasons: "1-12",
    bio: "A brilliant but socially awkward theoretical physicist from East Texas. With an IQ of 187, Sheldon holds a B.S., M.S., M.A., Ph.D., and Sc.D. He is known for his strict adherence to routine, his love of comic books and Star Trek, and his iconic catchphrase 'Bazinga!'",
    catchphrase: "Bazinga!",
    funFact: "Jim Parsons won 4 Emmy Awards and a Golden Globe for his portrayal of Sheldon Cooper.",
    traits: ["Genius IQ of 187", "Roommate Agreement enforcer", "Flash t-shirt collector", "Soft Kitty singer", "Nobel Prize winner"]
  },
  {
    id: "leonard",
    character: "Dr. Leonard Hofstadter",
    actor: "Johnny Galecki",
    color: "#22C55E",
    initials: "LH",
    role: "Experimental Physicist",
    seasons: "1-12",
    bio: "An experimental physicist at Caltech and Sheldon's long-suffering roommate. Leonard is the most socially adjusted of the group, serving as the bridge between the nerdy world of his friends and the 'normal' world represented by Penny.",
    catchphrase: "It's a little wrong to say a tomato is a vegetable; it's very wrong to say it's a suspension bridge.",
    funFact: "Johnny Galecki was the first person cast in the show, even before the pilot was reworked.",
    traits: ["Lactose intolerant", "Penny's husband", "Wears glasses", "Mother issues", "The 'normal' one"]
  },
  {
    id: "penny",
    character: "Penny Hofstadter",
    actor: "Kaley Cuoco",
    color: "#EC4899",
    initials: "P",
    role: "Pharmaceutical Sales Rep",
    seasons: "1-12",
    bio: "Originally from Omaha, Nebraska, Penny moved to Pasadena to pursue an acting career. She works as a waitress at The Cheesecake Factory before transitioning to a successful career in pharmaceutical sales. She becomes Leonard's wife and the heart of the group.",
    catchphrase: "Oh, honey...",
    funFact: "Penny's last name was never revealed until she married Leonard and took his surname, Hofstadter.",
    traits: ["From Nebraska", "Former Cheesecake Factory waitress", "Wine lover", "Street smart", "The group's social compass"]
  },
  {
    id: "howard",
    character: "Howard Wolowitz",
    actor: "Simon Helberg",
    color: "#EF4444",
    initials: "HW",
    role: "Aerospace Engineer",
    seasons: "1-12",
    bio: "An aerospace engineer at Caltech and a NASA astronaut who has been to the International Space Station. Howard is known for his flamboyant fashion sense, his impressions, and his close relationship with his overbearing mother.",
    catchphrase: "Hummina hummina hummina...",
    funFact: "Howard is the only main character without a doctoral degree, which the others frequently remind him of.",
    traits: ["NASA astronaut", "Master of impressions", "Mama's boy", "Belt buckle collector", "Only one without a PhD"]
  },
  {
    id: "raj",
    character: "Dr. Rajesh Koothrappali",
    actor: "Kunal Nayyar",
    color: "#A855F7",
    initials: "RK",
    role: "Astrophysicist",
    seasons: "1-12",
    bio: "An astrophysicist at Caltech originally from New Delhi, India. Raj initially suffered from selective mutism around women unless he consumed alcohol, a condition he eventually overcame. He is known for his romantic nature and metrosexual tendencies.",
    catchphrase: "Dude!",
    funFact: "Kunal Nayyar was born in London and raised in New Delhi, similar to his character's background.",
    traits: ["Selective mutism (early seasons)", "Hopeless romantic", "Dog lover (Cinnamon)", "Rich parents", "People magazine subscriber"]
  },
  {
    id: "bernadette",
    character: "Dr. Bernadette Rostenkowski-Wolowitz",
    actor: "Melissa Rauch",
    color: "#F59E0B",
    initials: "BR",
    role: "Microbiologist",
    seasons: "3-12",
    bio: "A microbiologist who works at a pharmaceutical company. Despite her tiny stature and high-pitched voice, Bernadette has a fierce personality. She meets Howard through Penny and eventually marries him.",
    catchphrase: "Howie!",
    funFact: "Melissa Rauch based Bernadette's distinctive high-pitched voice on her own mother's voice.",
    traits: ["Tiny but terrifying", "Highest earner of the group", "Mother of two", "Competitive nature", "Catholic upbringing"]
  },
  {
    id: "amy",
    character: "Dr. Amy Farrah Fowler",
    actor: "Mayim Bialik",
    color: "#14B8A6",
    initials: "AF",
    role: "Neurobiologist",
    seasons: "3-12",
    bio: "A neurobiologist who becomes Sheldon's girlfriend and eventually his wife. Amy was initially very similar to Sheldon in her social awkwardness, but she gradually becomes more outgoing, especially through her friendship with Penny and Bernadette.",
    catchphrase: "That's the kind of love I got from my mother. Conditional and begrudging.",
    funFact: "Mayim Bialik has a real Ph.D. in neuroscience from UCLA, just like her character.",
    traits: ["Real PhD in neuroscience", "Sheldon's wife", "Tiara lover", "Bestie with Penny", "Nobel Prize winner"]
  },
  {
    id: "stuart",
    character: "Stuart Bloom",
    actor: "Kevin Sussman",
    color: "#6B7280",
    initials: "SB",
    role: "Comic Book Store Owner",
    seasons: "2-12",
    bio: "The owner of The Comic Center of Pasadena, the gang's favorite comic book store. Stuart is characterized by his perpetual sadness, self-deprecating humor, and financial difficulties, but he's a beloved member of the extended friend group.",
    catchphrase: "I'm Stuart. I'm also poor and lonely.",
    funFact: "Kevin Sussman was originally a recurring character before being promoted to series regular in Season 6.",
    traits: ["Comic book store owner", "Self-deprecating humor", "Artist", "Lives with Howard's mom", "Perpetually broke"]
  }
];

const RECURRING_CAST = [
  { actor: "Wil Wheaton", character: "Himself", role: "Sheldon's nemesis turned friend", seasons: "3-12" },
  { actor: "Christine Baranski", character: "Dr. Beverly Hofstadter", role: "Leonard's intimidating mother", seasons: "2-12" },
  { actor: "Laurie Metcalf", character: "Mary Cooper", role: "Sheldon's devoutly religious mother", seasons: "1-12" },
  { actor: "Bob Newhart", character: "Professor Proton (Arthur Jeffries)", role: "Sheldon's childhood hero", seasons: "6-12" },
  { actor: "John Ross Bowie", character: "Barry Kripke", role: "Sheldon's rival at Caltech", seasons: "2-12" },
  { actor: "Brian Posehn", character: "Bert Kibbler", role: "Caltech geologist", seasons: "6-12" },
  { actor: "Regina King", character: "Mrs. Davis", role: "Caltech HR administrator", seasons: "6-10" },
  { actor: "Sara Gilbert", character: "Leslie Winkle", role: "Physicist, Leonard's ex", seasons: "1-3" },
  { actor: "Carol Ann Susi", character: "Mrs. Wolowitz (voice)", role: "Howard's overbearing mother", seasons: "1-8" },
  { actor: "Aarti Mann", character: "Priya Koothrappali", role: "Raj's sister, Leonard's ex", seasons: "4-5" },
  { actor: "Kate Micucci", character: "Lucy", role: "Raj's socially anxious girlfriend", seasons: "6-7" },
  { actor: "Laura Spencer", character: "Emily Sweeney", role: "Raj's dermatologist girlfriend", seasons: "7-9" },
  { actor: "Mark Hamill", character: "Himself", role: "Guest star in Howard & Bernadette's wedding", seasons: "11" },
  { actor: "Stephen Hawking", character: "Himself", role: "Legendary physicist guest appearances", seasons: "5-11" },
  { actor: "Stan Lee", character: "Himself", role: "Comic book legend", seasons: "3" },
  { actor: "Leonard Nimoy", character: "Himself (voice)", role: "Sheldon's Spock action figure", seasons: "5" },
  { actor: "Summer Glau", character: "Herself", role: "Firefly actress on a train", seasons: "2" },
  { actor: "James Earl Jones", character: "Himself", role: "Sheldon's surprise adventure buddy", seasons: "7" },
  { actor: "Neil deGrasse Tyson", character: "Himself", role: "Challenges Raj about Pluto", seasons: "4" }
];

const CREW = [
  { name: "Chuck Lorre", role: "Co-Creator, Executive Producer, Writer", note: "Creator of numerous hit sitcoms including Two and a Half Men and Mom" },
  { name: "Bill Prady", role: "Co-Creator, Executive Producer, Writer", note: "Drew on his own experience working with computer programmers" },
  { name: "Steven Molaro", role: "Showrunner (Seasons 8-12), Executive Producer, Writer", note: "Took over as showrunner when Bill Prady stepped back" },
  { name: "David Saltzberg", role: "Science Consultant", note: "UCLA professor who ensured all the science on whiteboards was accurate" },
  { name: "Mark Cendrowski", role: "Director (most episodes)", note: "Directed over 200 episodes of the series" },
  { name: "Ed Alonzo", role: "Science & Magic Consultant", note: "Helped create realistic lab and experiment scenes" },
  { name: "Barenaked Ladies", role: "Theme Song Performers", note: "Wrote and performed the iconic 'History of Everything' theme song" },
  { name: "John Shaffner", role: "Production Designer", note: "Designed the iconic apartment sets including the never-working elevator" },
  { name: "Mary T. Quigley", role: "Set Decorator", note: "Filled sets with authentic geek culture items and Easter eggs" },
  { name: "Nikki Valko & Ken Miller", role: "Casting Directors", note: "Assembled the perfectly cast ensemble" },
  { name: "Peter Chakos", role: "Editor", note: "Edited the majority of the series' episodes" },
  { name: "Eric Kaplan", role: "Executive Producer, Writer", note: "Wrote many fan-favorite episodes" },
  { name: "Jim Reynolds", role: "Executive Producer, Writer", note: "Key writer throughout the series" },
  { name: "Maria Ferrari", role: "Executive Producer, Writer", note: "Contributing writer across multiple seasons" },
  { name: "Anthony Del Broccolo", role: "Executive Producer, Writer", note: "Part of the core writing team" },
  { name: "Faye Oshima Belyeu", role: "Costume Designer", note: "Created each character's distinctive wardrobe style" }
];

// ── EPISODES DATA ──
const EPISODES = {
  1: [
    { ep: 1, title: "Pilot", date: "Sep 24, 2007", rating: 8.3, desc: "Leonard and Sheldon meet their new neighbor Penny, a beautiful aspiring actress from Nebraska. Leonard is instantly smitten, while Sheldon remains characteristically indifferent.", trivia: "The original unaired pilot had a different female lead named Katie, played by Amanda Walsh." },
    { ep: 2, title: "The Big Bran Hypothesis", date: "Oct 1, 2007", rating: 8.0, desc: "Leonard and Sheldon sneak into Penny's apartment to clean it while she sleeps, leading to an uncomfortable confrontation." },
    { ep: 3, title: "The Fuzzy Boots Corollary", date: "Oct 8, 2007", rating: 8.0, desc: "Leonard discovers Penny is seeing someone and tries to move on with a date at the bookstore." },
    { ep: 4, title: "The Luminous Fish Effect", date: "Oct 15, 2007", rating: 7.9, desc: "After insulting his new department head, Sheldon is suspended and takes up a series of new hobbies, including making glow-in-the-dark fish.", trivia: "First appearance of Laurie Metcalf as Sheldon's mother Mary Cooper." },
    { ep: 5, title: "The Hamburger Postulate", date: "Oct 22, 2007", rating: 8.0, desc: "Leonard begins a brief relationship with fellow physicist Leslie Winkle, while Sheldon struggles with any changes to the group dynamic." },
    { ep: 6, title: "The Middle-Earth Paradigm", date: "Oct 29, 2007", rating: 8.4, desc: "The guys attend Penny's Halloween party, where Leonard tries to impress her while dressed as Frodo.", trivia: "All four guys originally showed up as The Flash before changing costumes." },
    { ep: 7, title: "The Dumpling Paradox", date: "Nov 5, 2007", rating: 8.0, desc: "Howard begins sleeping with Penny's friend Christy, disrupting the group's Halo night and dumpling dinner plans." },
    { ep: 8, title: "The Grasshopper Experiment", date: "Nov 12, 2007", rating: 8.1, desc: "Raj discovers he can talk to women when drunk. His parents set him up on a blind date with Lalita Gupta." },
    { ep: 9, title: "The Cooper-Hofstadter Polarization", date: "Mar 17, 2008", rating: 8.2, desc: "Leonard and Sheldon have a falling out when Leonard wants to present their joint paper at a conference but Sheldon refuses." },
    { ep: 10, title: "The Loobenfeld Decay", date: "Mar 24, 2008", rating: 8.1, desc: "Leonard makes up an excuse to avoid seeing Penny's one-woman show, and Sheldon creates an elaborate cover story." },
    { ep: 11, title: "The Pancake Batter Anomaly", date: "Mar 31, 2008", rating: 8.3, desc: "Sheldon gets sick and becomes even more demanding than usual, driving Leonard and the others to hide from him.", trivia: "First time 'Soft Kitty' is sung on the show – it became an iconic recurring element." },
    { ep: 12, title: "The Jerusalem Duality", date: "Apr 14, 2008", rating: 8.0, desc: "A 15-year-old prodigy arrives at the university, threatening Sheldon's position as the smartest person around." },
    { ep: 13, title: "The Bat Jar Conjecture", date: "Apr 21, 2008", rating: 8.2, desc: "The guys form a Physics Bowl team but Sheldon's bossiness forces them to kick him out." },
    { ep: 14, title: "The Nerdvana Annihilation", date: "Apr 28, 2008", rating: 8.1, desc: "Leonard buys a full-size time machine prop from the 1960 film, causing issues with Penny." },
    { ep: 15, title: "The Porkchop Indeterminacy", date: "May 5, 2008", rating: 8.0, desc: "Sheldon's twin sister Missy visits, and all the guys compete for her attention except Sheldon." },
    { ep: 16, title: "The Peanut Reaction", date: "May 12, 2008", rating: 8.3, desc: "Penny learns Leonard has never had a birthday party and decides to throw him a surprise party." },
    { ep: 17, title: "The Tangerine Factor", date: "May 19, 2008", rating: 8.5, desc: "Leonard and Penny finally go on their first date. Sheldon gets a cat.", trivia: "The Season 1 finale marks the beginning of Leonard and Penny's relationship." }
  ],
  2: [
    { ep: 1, title: "The Bad Fish Paradigm", date: "Sep 22, 2008", rating: 8.1, desc: "Penny tells Sheldon a secret about why she ended her date with Leonard, putting Sheldon in an uncomfortable position." },
    { ep: 2, title: "The Codpiece Topology", date: "Sep 29, 2008", rating: 8.0, desc: "Leonard dates Leslie Winkle to get over Penny, while Sheldon feuds with Leslie over string theory vs. loop quantum gravity." },
    { ep: 3, title: "The Barbarian Sublimation", date: "Oct 6, 2008", rating: 8.0, desc: "Penny becomes addicted to online gaming (Age of Conan) after a series of bad dates." },
    { ep: 4, title: "The Griffin Equivalency", date: "Oct 13, 2008", rating: 8.0, desc: "Raj is featured in People magazine's '30 Under 30 to Watch' list and becomes insufferably arrogant." },
    { ep: 5, title: "The Euclid Alternative", date: "Oct 20, 2008", rating: 8.2, desc: "Sheldon's refusal to learn to drive forces his friends to chauffeur him around, testing their patience." },
    { ep: 6, title: "The Cooper-Nowitzki Theorem", date: "Nov 3, 2008", rating: 8.1, desc: "A graduate student named Ramona becomes obsessed with Sheldon and moves in to ensure he focuses on his work." },
    { ep: 7, title: "The Panty Piñata Polarization", date: "Nov 10, 2008", rating: 8.3, desc: "Penny gets banned from the apartment by Sheldon over a trivial violation, leading to an escalating war between them." },
    { ep: 8, title: "The Lizard-Spock Expansion", date: "Nov 17, 2008", rating: 8.5, desc: "Howard starts dating Stephanie, a surgical resident, and Leonard becomes jealous.", trivia: "First mention of 'Rock, Paper, Scissors, Lizard, Spock' – a game that became a cultural phenomenon." },
    { ep: 9, title: "The White Asparagus Triangulation", date: "Nov 24, 2008", rating: 8.0, desc: "Sheldon tries to ensure Leonard's relationship with Stephanie succeeds so she can serve as the group's personal physician." },
    { ep: 10, title: "The Vartabedian Conundrum", date: "Dec 8, 2008", rating: 8.0, desc: "Leonard realizes that Stephanie has essentially moved in with him without his knowledge." },
    { ep: 11, title: "The Bath Item Gift Hypothesis", date: "Dec 15, 2008", rating: 9.1, desc: "Sheldon agonizes over finding the perfect Christmas gift for Penny, not knowing what she'll get him. When she gives him a napkin signed by Leonard Nimoy, he gives her every gift basket he bought and a rare hug.", trivia: "One of the highest-rated episodes ever. Sheldon's hug became one of the most iconic moments in sitcom history." },
    { ep: 12, title: "The Killer Robot Instability", date: "Jan 12, 2009", rating: 8.0, desc: "The guys build a killer robot for a competition, but Penny hurts Howard's feelings with a harsh rejection." },
    { ep: 13, title: "The Friendship Algorithm", date: "Jan 19, 2009", rating: 8.4, desc: "Sheldon creates a flowchart algorithm to make friends with Barry Kripke to gain access to a computer.", trivia: "The friendship algorithm flowchart became a popular poster among fans." },
    { ep: 14, title: "The Financial Permeability", date: "Feb 2, 2009", rating: 8.0, desc: "Sheldon lends Penny money when she can't pay rent, and she becomes overwhelmed by the debt." },
    { ep: 15, title: "The Maternal Capacitance", date: "Feb 9, 2009", rating: 8.3, desc: "Leonard's psychiatrist mother Beverly visits and bonds with Sheldon while making Leonard feel inadequate.", trivia: "First appearance of Christine Baranski as Beverly Hofstadter." },
    { ep: 16, title: "The Cushion Saturation", date: "Mar 2, 2009", rating: 8.2, desc: "Penny accidentally shoots a paintball gun at Sheldon's beloved spot on the couch." },
    { ep: 17, title: "The Terminator Decoupling", date: "Mar 9, 2009", rating: 8.2, desc: "The guys take a train to a science symposium and encounter Summer Glau. Sheldon realizes he left a flash drive at home." },
    { ep: 18, title: "The Work Song Nanocluster", date: "Mar 16, 2009", rating: 8.0, desc: "Sheldon helps Penny start a business selling 'Penny Blossoms' hair accessories, applying industrial engineering principles." },
    { ep: 19, title: "The Dead Hooker Juxtaposition", date: "Mar 30, 2009", rating: 8.1, desc: "A beautiful new neighbor moves in upstairs, and Penny becomes jealous when the guys pay attention to her." },
    { ep: 20, title: "The Hofstadter Isotope", date: "Apr 27, 2009", rating: 8.0, desc: "Penny goes on a date with Stuart from the comic book store, making Leonard jealous." },
    { ep: 21, title: "The Vegas Renormalization", date: "May 4, 2009", rating: 8.1, desc: "After Howard and Leslie break up, the guys take him to Las Vegas to cheer him up." },
    { ep: 22, title: "The Classified Materials Turbulence", date: "May 11, 2009", rating: 8.2, desc: "Howard discovers a design flaw in his space toilet project for the ISS, and the guys scramble to fix it." },
    { ep: 23, title: "The Monopolar Expedition", date: "May 18, 2009", rating: 8.6, desc: "Sheldon is offered a three-month expedition to the North Pole. Penny reveals her feelings for Leonard before they leave.", trivia: "Season 2 finale. Penny's 'Oh boy' after telling Leonard she'll miss him became an iconic moment." }
  ],
  3: [
    { ep: 1, title: "The Electric Can Opener Fluctuation", date: "Sep 21, 2009", rating: 8.3, desc: "The guys return from the North Pole and Sheldon discovers they tampered with his experiment results." },
    { ep: 2, title: "The Jiminy Conjecture", date: "Sep 28, 2009", rating: 7.9, desc: "Sheldon and Howard make a bet about the species of a cricket. Leonard and Penny go on their first real date." },
    { ep: 3, title: "The Gothowitz Deviation", date: "Oct 5, 2009", rating: 8.1, desc: "Sheldon tries to modify Penny's behavior using chocolate rewards. Howard and Raj visit a goth nightclub." },
    { ep: 4, title: "The Pirate Solution", date: "Oct 12, 2009", rating: 8.0, desc: "Raj faces deportation when his research funding is cut, so Sheldon reluctantly hires him as his assistant." },
    { ep: 5, title: "The Creepy Candy Coating Corollary", date: "Oct 19, 2009", rating: 8.2, desc: "Sheldon faces off against Wil Wheaton in a card game tournament. Howard goes on a date arranged by Bernadette.", trivia: "First appearances of both Wil Wheaton as Sheldon's nemesis and Melissa Rauch as Bernadette." },
    { ep: 6, title: "The Cornhusker Vortex", date: "Nov 2, 2009", rating: 7.9, desc: "Leonard tries to learn about football to fit in with Penny's friends." },
    { ep: 7, title: "The Guitarist Amplification", date: "Nov 9, 2009", rating: 7.9, desc: "Leonard and Penny fight about her ex-boyfriend staying at her apartment, and Sheldon suffers from their arguing." },
    { ep: 8, title: "The Adhesive Duck Deficiency", date: "Nov 16, 2009", rating: 8.7, desc: "Penny dislocates her shoulder and Sheldon must drive her to the hospital. The other guys get high on cookies in the desert.", trivia: "Fan-favorite episode. Sheldon singing 'Soft Kitty' in the car became legendary." },
    { ep: 9, title: "The Vengeance Formulation", date: "Nov 23, 2009", rating: 8.0, desc: "Sheldon plots revenge against Barry Kripke for a prank. Howard imagines life with Bernadette." },
    { ep: 10, title: "The Gorilla Experiment", date: "Dec 7, 2009", rating: 8.1, desc: "Bernadette asks Sheldon to teach her physics so she can understand Howard's work." },
    { ep: 11, title: "The Maternal Congruence", date: "Dec 14, 2009", rating: 8.3, desc: "Leonard's mother Beverly visits for the holidays and reveals she's getting divorced." },
    { ep: 12, title: "The Psychic Vortex", date: "Jan 11, 2010", rating: 7.9, desc: "Sheldon accompanies Raj to a university mixer and meets a woman interested in him." },
    { ep: 13, title: "The Bozeman Reaction", date: "Jan 18, 2010", rating: 8.2, desc: "After their apartment is robbed, Sheldon decides to move to Bozeman, Montana." },
    { ep: 14, title: "The Einstein Approximation", date: "Feb 1, 2010", rating: 8.2, desc: "Sheldon gets a menial job at The Cheesecake Factory to solve a physics problem, following Einstein's example." },
    { ep: 15, title: "The Large Hadron Collision", date: "Feb 8, 2010", rating: 8.1, desc: "Leonard wins a trip to see the Large Hadron Collider in Switzerland and must choose between taking Penny or Sheldon." },
    { ep: 16, title: "The Excelsior Acquisition", date: "Mar 1, 2010", rating: 8.2, desc: "Sheldon misses meeting Stan Lee at the comic book store because of a traffic court appearance.", trivia: "Stan Lee's cameo, including the restraining order ending, is one of the show's funniest moments." },
    { ep: 17, title: "The Precious Fragmentation", date: "Mar 8, 2010", rating: 8.3, desc: "The guys find a ring from The Lord of the Rings at a garage sale and fight over who gets to keep it." },
    { ep: 18, title: "The Pants Alternative", date: "Mar 22, 2010", rating: 8.3, desc: "Sheldon must give a speech at an awards banquet and his friends try different methods to help with his stage fright." },
    { ep: 19, title: "The Wheaton Recurrence", date: "Apr 12, 2010", rating: 8.4, desc: "Wil Wheaton manipulates Penny during a bowling match, causing Leonard and Penny to break up." },
    { ep: 20, title: "The Spaghetti Catalyst", date: "May 3, 2010", rating: 8.0, desc: "After Leonard and Penny break up, Sheldon tries to maintain friendships with both of them separately." },
    { ep: 21, title: "The Plimpton Stimulation", date: "May 10, 2010", rating: 8.0, desc: "A renowned female physicist visits and sleeps with Leonard, then tries to sleep with Sheldon and Raj." },
    { ep: 22, title: "The Staircase Implementation", date: "May 17, 2010", rating: 8.9, desc: "Leonard tells Penny the story of how he and Sheldon became roommates and how the elevator broke.", trivia: "This flashback episode revealing the broken elevator origin story is one of the highest-rated episodes of the entire series." },
    { ep: 23, title: "The Lunar Excitation", date: "May 24, 2010", rating: 8.6, desc: "Raj and Howard find Amy Farrah Fowler on a dating site for Sheldon. Penny sleeps with Raj (sort of).", trivia: "First appearance of Mayim Bialik as Amy Farrah Fowler, introduced in the season finale." }
  ],
  4: [
    { ep: 1, title: "The Robotic Manipulation", date: "Sep 23, 2010", rating: 8.1, desc: "Sheldon goes on his first date with Amy, chaperoned by Penny. Howard gets his hand stuck in a robot arm." },
    { ep: 2, title: "The Cruciferous Vegetable Amplification", date: "Sep 30, 2010", rating: 8.0, desc: "Sheldon calculates he won't live long enough to transfer his consciousness to a robot, so he creates a 'virtual presence device.'" },
    { ep: 3, title: "The Zazzy Substitution", date: "Oct 7, 2010", rating: 8.2, desc: "After Sheldon and Amy break up, Sheldon adopts 25 cats. His mother is called in to intervene." },
    { ep: 4, title: "The Hot Troll Deviation", date: "Oct 14, 2010", rating: 8.0, desc: "Howard and Bernadette rekindle their relationship. Sheldon feuds with Raj's new desk placement." },
    { ep: 5, title: "The Desperation Emanation", date: "Oct 21, 2010", rating: 8.1, desc: "Leonard feels left out as the only one without a girlfriend, so he lets Howard set him up on a blind date." },
    { ep: 6, title: "The Irish Pub Formulation", date: "Nov 4, 2010", rating: 8.1, desc: "Leonard secretly dates Raj's sister Priya. Sheldon must keep the secret, which is torture for him." },
    { ep: 7, title: "The Apology Insufficiency", date: "Nov 4, 2010", rating: 8.4, desc: "Howard's security clearance is jeopardized when an FBI agent interviews the guys about him." },
    { ep: 8, title: "The 21-Second Excitation", date: "Nov 11, 2010", rating: 8.0, desc: "The guys camp out for a special screening of Raiders of the Lost Ark. Penny, Bernadette, and Amy have a slumber party." },
    { ep: 9, title: "The Boyfriend Complexity", date: "Nov 18, 2010", rating: 8.1, desc: "Penny pretends to be back with Leonard to impress her visiting father. Raj discovers Howard's secret about the Mars rover." },
    { ep: 10, title: "The Alien Parasite Hypothesis", date: "Dec 9, 2010", rating: 8.3, desc: "Amy experiences physical attraction for the first time — to Penny's ex-boyfriend Zack." },
    { ep: 11, title: "The Justice League Recombination", date: "Dec 16, 2010", rating: 8.3, desc: "The gang dresses up as the Justice League for a costume contest at the comic book store." },
    { ep: 12, title: "The Bus Pants Utilization", date: "Jan 6, 2011", rating: 8.1, desc: "Leonard has an idea for a smartphone app and leads the guys in developing it, causing tension with Sheldon." },
    { ep: 13, title: "The Love Car Displacement", date: "Jan 20, 2011", rating: 8.1, desc: "The gang attends a science conference and must share hotel rooms, leading to awkward situations." },
    { ep: 14, title: "The Thespian Catalyst", date: "Feb 3, 2011", rating: 8.0, desc: "Sheldon takes acting classes from Penny after receiving negative student reviews." },
    { ep: 15, title: "The Benefactor Factor", date: "Feb 10, 2011", rating: 8.0, desc: "Leonard considers sleeping with a wealthy university donor to secure funding for the physics department." },
    { ep: 16, title: "The Cohabitation Formulation", date: "Feb 17, 2011", rating: 8.1, desc: "Bernadette asks Howard to choose between her and his mother. Penny and Raj become uncomfortable fifth wheels." },
    { ep: 17, title: "The Toast Derivation", date: "Feb 24, 2011", rating: 8.0, desc: "Sheldon tries to form a new social group when he realizes Leonard is the nucleus of their friend group." },
    { ep: 18, title: "The Prestidigitation Approximation", date: "Mar 10, 2011", rating: 8.0, desc: "Sheldon becomes obsessed with figuring out how Howard does a card trick. Priya makes Leonard cut ties with Penny." },
    { ep: 19, title: "The Zarnecki Incursion", date: "Mar 31, 2011", rating: 8.2, desc: "When Sheldon's World of Warcraft account is hacked, the guys go on a real-life quest to find the hacker." },
    { ep: 20, title: "The Herb Garden Germination", date: "Apr 7, 2011", rating: 8.3, desc: "Sheldon and Amy study gossip by spreading rumors. Howard plans to propose to Bernadette." },
    { ep: 21, title: "The Agreement Dissection", date: "Apr 28, 2011", rating: 8.5, desc: "Amy, Bernadette, and Penny have a girls' night out. Amy kisses Sheldon after getting drunk." },
    { ep: 22, title: "The Wildebeest Implementation", date: "May 5, 2011", rating: 8.0, desc: "Sheldon creates a three-person chess game. Amy manipulates Bernadette to spy on Priya for Penny." },
    { ep: 23, title: "The Engagement Reaction", date: "May 12, 2011", rating: 8.3, desc: "Howard tells his mother about his engagement to Bernadette, and she ends up in the hospital." },
    { ep: 24, title: "The Roommate Transmogrification", date: "May 19, 2011", rating: 8.6, desc: "Raj wakes up in bed with Penny. Bernadette gets her PhD. Sheldon asks Amy to be his girlfriend.", trivia: "Season finale where Sheldon officially asks Amy to be his girlfriend — 'I'm not crazy; my mother had me tested.'" }
  ],
  5: [
    { ep: 1, title: "The Skank Reflex Analysis", date: "Sep 22, 2011", rating: 8.0, desc: "The gang deals with the aftermath of Raj and Penny's night together (which turns out to be not what everyone thinks)." },
    { ep: 2, title: "The Infestation Hypothesis", date: "Sep 29, 2011", rating: 8.0, desc: "Sheldon is horrified when Penny brings a chair from the street into her apartment." },
    { ep: 3, title: "The Pulled Groin Extrapolation", date: "Oct 6, 2011", rating: 8.1, desc: "Amy takes Leonard as her date to a wedding and they enjoy a surprisingly good time." },
    { ep: 4, title: "The Wiggly Finger Catalyst", date: "Oct 6, 2011", rating: 8.0, desc: "Raj starts dating a deaf girl named Emily. Sheldon creates a virtual Siri-like assistant." },
    { ep: 5, title: "The Russian Rocket Reaction", date: "Oct 13, 2011", rating: 8.2, desc: "Howard is offered a chance to go to space on a Russian Soyuz rocket." },
    { ep: 6, title: "The Rhinitis Revelation", date: "Oct 20, 2011", rating: 8.1, desc: "Sheldon's mother visits and Sheldon is upset when she spends time with the rest of the group." },
    { ep: 7, title: "The Good Guy Fluctuation", date: "Oct 27, 2011", rating: 8.1, desc: "Leonard is attracted to a girl at the comic book store. The guys try to scare each other for Halloween." },
    { ep: 8, title: "The Isolation Permutation", date: "Nov 3, 2011", rating: 8.2, desc: "Amy is hurt when Penny and Bernadette go bridesmaid dress shopping without her." },
    { ep: 9, title: "The Ornithophobia Diffusion", date: "Nov 10, 2011", rating: 8.0, desc: "Sheldon tries to overcome his fear of birds. Leonard and Penny go on a 'just friends' date." },
    { ep: 10, title: "The Flaming Spittoon Acquisition", date: "Nov 17, 2011", rating: 8.6, desc: "When Stuart asks Amy out, Sheldon becomes jealous and draws up a 'Relationship Agreement.' He asks Amy to be his girlfriend.", trivia: "The episode that officially establishes Sheldon and Amy's relationship with a formal agreement." },
    { ep: 11, title: "The Speckerman Recurrence", date: "Dec 1, 2011", rating: 8.0, desc: "Leonard's high school bully reaches out, and Leonard confronts him." },
    { ep: 12, title: "The Shiny Trinket Maneuver", date: "Jan 12, 2012", rating: 8.2, desc: "Sheldon upsets Amy by being dismissive of her research paper. Howard learns Bernadette doesn't want children." },
    { ep: 13, title: "The Recombination Hypothesis", date: "Jan 19, 2012", rating: 8.4, desc: "Leonard asks Penny out on a spur-of-the-moment date, and they imagine how getting back together would go." },
    { ep: 14, title: "The Beta Test Initiation", date: "Jan 26, 2012", rating: 8.1, desc: "Leonard and Penny get back together and use a beta-testing approach for their relationship." },
    { ep: 15, title: "The Friendship Contraction", date: "Feb 2, 2012", rating: 8.2, desc: "Leonard demotes Sheldon in their friendship after growing tired of being his designated driver." },
    { ep: 16, title: "The Vacation Solution", date: "Feb 9, 2012", rating: 8.1, desc: "Sheldon is forced to take a vacation and ends up working in Amy's neurobiology lab." },
    { ep: 17, title: "The Rothman Disintegration", date: "Feb 16, 2012", rating: 8.0, desc: "Sheldon and Kripke compete for a vacant office. Amy gives Penny a huge painting of the two of them." },
    { ep: 18, title: "The Werewolf Transformation", date: "Mar 8, 2012", rating: 8.0, desc: "Sheldon spirals when his barber is hospitalized and can't cut his hair on schedule." },
    { ep: 19, title: "The Weekend Vortex", date: "Mar 29, 2012", rating: 8.0, desc: "The guys want to play Star Wars: The Old Republic all weekend, but Amy and Bernadette have other plans." },
    { ep: 20, title: "The Transporter Malfunction", date: "Mar 29, 2012", rating: 8.1, desc: "Leonard and Sheldon receive vintage Star Trek transporter toys. Raj considers adopting a child." },
    { ep: 21, title: "The Hawking Excitation", date: "Apr 5, 2012", rating: 8.6, desc: "Howard gets to work with Stephen Hawking and Sheldon will do anything to meet him.", trivia: "First appearance of Stephen Hawking, who becomes a recurring guest star." },
    { ep: 22, title: "The Stag Convergence", date: "Apr 26, 2012", rating: 8.0, desc: "The guys throw Howard a bachelor party. Bernadette is upset when an embarrassing video goes viral." },
    { ep: 23, title: "The Launch Acceleration", date: "May 3, 2012", rating: 8.4, desc: "Howard prepares for his space launch. Leonard accidentally tells Penny he loves her during sex." },
    { ep: 24, title: "The Countdown Reflection", date: "May 10, 2012", rating: 8.9, desc: "Howard launches into space aboard the Soyuz rocket. Howard and Bernadette get married via video link while he's in orbit.", trivia: "Howard's wedding in space is one of the most emotional season finales." }
  ],
  6: [
    { ep: 1, title: "The Date Night Variable", date: "Sep 27, 2012", rating: 8.0, desc: "Raj crashes Sheldon and Amy's anniversary dinner. Howard adjusts to life on the ISS." },
    { ep: 2, title: "The Decoupling Fluctuation", date: "Oct 4, 2012", rating: 8.0, desc: "Penny has doubts about her relationship with Leonard. Howard annoys his crewmates in space." },
    { ep: 3, title: "The Higgs Boson Observation", date: "Oct 11, 2012", rating: 8.1, desc: "Sheldon hires grad student Alex Jensen as his assistant. Amy becomes jealous of Sheldon's attention." },
    { ep: 4, title: "The Re-Entry Minimization", date: "Oct 18, 2012", rating: 8.3, desc: "Howard returns from space but nobody cares as much as he expected." },
    { ep: 5, title: "The Holographic Excitation", date: "Oct 25, 2012", rating: 8.2, desc: "Howard won't stop talking about space. It's Halloween at Stuart's comic book store." },
    { ep: 6, title: "The Extract Obliteration", date: "Nov 1, 2012", rating: 8.1, desc: "Sheldon plays Words With Friends with Stephen Hawking. Penny secretly enrolls in a college class." },
    { ep: 7, title: "The Habitation Configuration", date: "Nov 8, 2012", rating: 8.0, desc: "Sheldon confronts Wil Wheaton about his treatment of Amy on Fun With Flags. Howard moves out of his mother's house." },
    { ep: 8, title: "The 43 Peculiarity", date: "Nov 15, 2012", rating: 8.0, desc: "Raj and Howard investigate what Sheldon does alone every afternoon for 20 minutes." },
    { ep: 9, title: "The Parking Spot Escalation", date: "Nov 29, 2012", rating: 8.3, desc: "Howard and Sheldon fight over a parking spot at the university. The argument escalates to involve everyone." },
    { ep: 10, title: "The Fish Guts Displacement", date: "Dec 6, 2012", rating: 8.2, desc: "Sheldon takes care of a sick Amy. Howard tries to bond with Bernadette's father through fishing." },
    { ep: 11, title: "The Santa Simulation", date: "Dec 13, 2012", rating: 8.2, desc: "The guys play a D&D-themed Christmas game. Raj takes a date to a holiday party." },
    { ep: 12, title: "The Egg Salad Equivalency", date: "Jan 3, 2013", rating: 8.1, desc: "Sheldon gets in trouble with HR when he tries to handle Alex's crush on Leonard." },
    { ep: 13, title: "The Bakersfield Expedition", date: "Jan 10, 2013", rating: 8.5, desc: "The guys are robbed while cosplaying on the way to a comic convention. The girls read comic books.", trivia: "One of the funniest episodes — the girls arguing about Thor's hammer is priceless." },
    { ep: 14, title: "The Cooper/Kripke Inversion", date: "Jan 31, 2013", rating: 8.0, desc: "Sheldon must collaborate with Kripke and discovers Kripke's work is better than his." },
    { ep: 15, title: "The Spoiler Alert Segmentation", date: "Feb 7, 2013", rating: 8.2, desc: "Leonard tries to move in with Penny after a fight with Sheldon about spoilers." },
    { ep: 16, title: "The Tangible Affection Proof", date: "Feb 14, 2013", rating: 8.1, desc: "On Valentine's Day, Sheldon gets Amy a gift that surprises everyone. Howard writes Bernadette a song." },
    { ep: 17, title: "The Monster Isolation", date: "Feb 21, 2013", rating: 8.0, desc: "Raj becomes a hermit after a date goes badly. Penny gets an acting role in a low-budget film." },
    { ep: 18, title: "The Contractual Obligation Implementation", date: "Mar 7, 2013", rating: 8.1, desc: "The guys visit a middle school to inspire young women in science. The girls visit Disneyland." },
    { ep: 19, title: "The Closet Reconfiguration", date: "Mar 14, 2013", rating: 8.5, desc: "Howard finds a letter from his estranged father. Each friend tells him a different version of what the letter says.", trivia: "An unexpectedly emotional episode about Howard's dad that left audiences in tears." },
    { ep: 20, title: "The Tenure Turbulence", date: "Apr 4, 2013", rating: 8.0, desc: "Sheldon, Leonard, Raj, and Kripke compete for a tenured position at the university." },
    { ep: 21, title: "The Closure Alternative", date: "Apr 25, 2013", rating: 8.1, desc: "Sheldon struggles with unresolved storylines from cancelled TV shows. Amy tries to help him find closure." },
    { ep: 22, title: "The Proton Resurgence", date: "May 2, 2013", rating: 8.3, desc: "Sheldon and Leonard hire Professor Proton (Bob Newhart), a former children's TV science host.", trivia: "First appearance of Bob Newhart as Professor Proton, Sheldon's childhood hero." },
    { ep: 23, title: "The Love Spell Potential", date: "May 9, 2013", rating: 8.5, desc: "The girls join the guys' D&D game. Sheldon and Amy's characters get intimate, and it affects them in real life." },
    { ep: 24, title: "The Bon Voyage Reaction", date: "May 16, 2013", rating: 8.4, desc: "Leonard is offered a research position on Stephen Hawking's team on a ship in the North Sea. Raj finally talks to a woman without alcohol.", trivia: "Raj overcomes his selective mutism, a major character milestone." }
  ],
  7: [
    { ep: 1, title: "The Hofstadter Insufficiency", date: "Sep 26, 2013", rating: 8.0, desc: "With Leonard away at sea, Penny and Sheldon bond over missing him. Raj's new ability to talk to women leads to oversharing." },
    { ep: 2, title: "The Deception Verification", date: "Oct 3, 2013", rating: 8.2, desc: "Leonard returns from the North Sea. Sheldon feels betrayed when Leonard spends time with Penny instead of him." },
    { ep: 3, title: "The Scavenger Vortex", date: "Oct 3, 2013", rating: 8.3, desc: "Raj creates an elaborate scavenger hunt with unusual pairings: Sheldon & Penny, Leonard & Bernadette, Howard & Amy." },
    { ep: 4, title: "The Raiders Minimization", date: "Oct 10, 2013", rating: 8.1, desc: "Amy ruins Raiders of the Lost Ark for Sheldon by pointing out that Indiana Jones is irrelevant to the plot." },
    { ep: 5, title: "The Workplace Proximity", date: "Oct 17, 2013", rating: 8.0, desc: "Amy starts working at Caltech near Sheldon, and he's not happy about it." },
    { ep: 6, title: "The Romance Resonance", date: "Oct 24, 2013", rating: 8.4, desc: "Howard performs a heartfelt song for Bernadette while she's in quarantine. Sheldon makes a scientific discovery.", trivia: "Howard's 'If I Didn't Have You' song for Bernadette is one of the show's most romantic moments." },
    { ep: 7, title: "The Proton Displacement", date: "Nov 7, 2013", rating: 8.1, desc: "Sheldon is jealous when Professor Proton bonds with Leonard instead of him." },
    { ep: 8, title: "The Itchy Brain Simulation", date: "Nov 14, 2013", rating: 8.2, desc: "Sheldon forces Leonard to wear an itchy sweater until he returns an overdue DVD." },
    { ep: 9, title: "The Thanksgiving Decoupling", date: "Nov 21, 2013", rating: 8.3, desc: "The gang has Thanksgiving at Howard's mother's house. Penny reveals she may have married Zack in Las Vegas." },
    { ep: 10, title: "The Discovery Dissipation", date: "Dec 5, 2013", rating: 8.0, desc: "Sheldon struggles when his accidental discovery makes him famous but he can't replicate it." },
    { ep: 11, title: "The Cooper Extraction", date: "Dec 12, 2013", rating: 8.7, desc: "When Sheldon goes to Texas for the holidays, the gang imagines what their lives would be like without him.", trivia: "The 'It's a Wonderful Life'-style episode exploring how Sheldon impacted everyone's lives." },
    { ep: 12, title: "The Hesitation Ramification", date: "Jan 2, 2014", rating: 8.3, desc: "Penny's scene in NCIS gets cut, devastating her. She proposes to Leonard while drunk." },
    { ep: 13, title: "The Occupation Recalibration", date: "Jan 9, 2014", rating: 8.0, desc: "Penny quits The Cheesecake Factory to focus on acting. Sheldon takes a mandatory vacation." },
    { ep: 14, title: "The Convention Conundrum", date: "Jan 30, 2014", rating: 8.6, desc: "When the guys can't get Comic-Con tickets, Sheldon goes to James Earl Jones' house and they have an epic night out.", trivia: "James Earl Jones and Sheldon's wild night out became an instant classic episode." },
    { ep: 15, title: "The Locomotive Manipulation", date: "Feb 6, 2014", rating: 8.4, desc: "Sheldon and Amy go on a Valentine's train date. They share their first real kiss.", trivia: "Sheldon and Amy's first proper kiss — a milestone moment for 'Shamy' fans." },
    { ep: 16, title: "The Table Polarization", date: "Feb 27, 2014", rating: 8.0, desc: "The group gets a dining table, which Sheldon resists. Howard worries about his career compared to Bernadette's." },
    { ep: 17, title: "The Friendship Turbulence", date: "Mar 6, 2014", rating: 8.0, desc: "Sheldon and Howard try to be nicer to each other. Penny gets an audition for a movie." },
    { ep: 18, title: "The Mommy Observation", date: "Mar 13, 2014", rating: 8.2, desc: "Sheldon visits his mother and discovers she has a secret boyfriend. Raj hosts a murder mystery party." },
    { ep: 19, title: "The Indecision Amalgamation", date: "Apr 3, 2014", rating: 8.0, desc: "Sheldon can't decide between an Xbox One and PS4. Penny considers a role in a bad movie." },
    { ep: 20, title: "The Relationship Diremption", date: "Apr 10, 2014", rating: 8.2, desc: "Sheldon considers giving up string theory after a drunk night. Raj goes on a date with Emily." },
    { ep: 21, title: "The Anything Can Happen Recurrence", date: "Apr 24, 2014", rating: 8.0, desc: "The gang tries to have a spontaneous night out but ends up spying on each other." },
    { ep: 22, title: "The Proton Transmogrification", date: "May 1, 2014", rating: 8.7, desc: "Professor Proton passes away and appears as a Force ghost to Sheldon on Star Wars Day (May 4th).", trivia: "An incredibly touching episode. Sheldon's grief for Professor Proton is genuinely moving." },
    { ep: 23, title: "The Gorilla Dissolution", date: "May 8, 2014", rating: 8.6, desc: "Penny gets fired from her movie and starts working in pharmaceuticals. Leonard proposes to Penny and she says yes!", trivia: "Leonard and Penny get engaged! A major milestone after seven seasons." },
    { ep: 24, title: "The Status Quo Combustion", date: "May 15, 2014", rating: 8.5, desc: "The comic book store burns down. Sheldon is overwhelmed by changes and considers leaving Pasadena." }
  ],
  8: [
    { ep: 1, title: "The Locomotion Interruption", date: "Sep 22, 2014", rating: 8.0, desc: "Sheldon is found at a train station in Arizona after his solo trip goes wrong. Penny starts her pharmaceutical sales job." },
    { ep: 2, title: "The Junior Professor Solution", date: "Sep 29, 2014", rating: 8.0, desc: "Sheldon must teach a class as a junior professor and Howard is his only student." },
    { ep: 3, title: "The First Pitch Insufficiency", date: "Oct 6, 2014", rating: 7.9, desc: "Howard throws out the first pitch at an Angels game (badly). Leonard and Penny have relationship doubts." },
    { ep: 4, title: "The Hook-Up Reverberation", date: "Oct 13, 2014", rating: 8.0, desc: "The guys consider investing in Stuart's comic book store reopening. Raj worries about Emily's darkness." },
    { ep: 5, title: "The Focus Attenuation", date: "Oct 20, 2014", rating: 8.0, desc: "The guys try to come up with an invention but keep getting distracted. The girls go to Las Vegas." },
    { ep: 6, title: "The Expedition Approximation", date: "Oct 27, 2014", rating: 8.0, desc: "Sheldon and Raj explore living in a mine to prep for possible dark matter research. Howard and Bernadette worry about money." },
    { ep: 7, title: "The Misinterpretation Agitation", date: "Nov 6, 2014", rating: 8.0, desc: "A doctor from Penny's work shows up at the apartment thinking they had a date. He turns out to be brilliant." },
    { ep: 8, title: "The Prom Equivalency", date: "Nov 13, 2014", rating: 8.5, desc: "The gang throws a prom on the roof of the building. Sheldon tells Amy he loves her for the first time.", trivia: "Sheldon's panic-driven but sincere 'I love you' to Amy is one of the show's most memorable moments." },
    { ep: 9, title: "The Septum Deviation", date: "Nov 20, 2014", rating: 8.0, desc: "Leonard needs surgery and Sheldon has trouble dealing with the possibility of losing his roommate." },
    { ep: 10, title: "The Champagne Reflection", date: "Dec 11, 2014", rating: 8.1, desc: "Sheldon records the final episode of Fun With Flags. Howard and the guys discover a dead professor's unpublished findings." },
    { ep: 11, title: "The Clean Room Infiltration", date: "Dec 11, 2014", rating: 8.2, desc: "Sheldon throws Amy a Victorian-style Christmas party because Amy hates Christmas." },
    { ep: 12, title: "The Space Probe Disintegration", date: "Jan 8, 2015", rating: 8.1, desc: "Raj panics when a space probe he designed nears its destination. Sheldon goes shopping with Penny." },
    { ep: 13, title: "The Anxiety Optimization", date: "Jan 29, 2015", rating: 8.0, desc: "Sheldon uses anxiety to boost his scientific output. Raj and Howard build a drone." },
    { ep: 14, title: "The Troll Manifestation", date: "Feb 5, 2015", rating: 8.0, desc: "Leonard and Sheldon publish a paper that gets attacked online by Stephen Hawking." },
    { ep: 15, title: "The Comic Book Store Regeneration", date: "Feb 19, 2015", rating: 8.7, desc: "Stuart's comic book store reopens. Howard's mother, Mrs. Wolowitz, passes away.", trivia: "Carol Ann Susi, who voiced Mrs. Wolowitz, had passed away in real life. The episode was a touching tribute." },
    { ep: 16, title: "The Intimacy Acceleration", date: "Feb 26, 2015", rating: 8.2, desc: "Sheldon and Penny try an experiment about accelerating intimacy. The gang plays 'Never Have I Ever.'" },
    { ep: 17, title: "The Colonization Application", date: "Mar 5, 2015", rating: 8.1, desc: "Sheldon and Amy apply to be colonists on Mars. Howard discovers a hidden room at Bernadette's house." },
    { ep: 18, title: "The Leftover Thermalization", date: "Mar 12, 2015", rating: 8.1, desc: "The gang eats Mrs. Wolowitz's frozen food for the last time as Howard finally says goodbye." },
    { ep: 19, title: "The Skywalker Incursion", date: "Apr 2, 2015", rating: 8.2, desc: "Leonard and Sheldon try to visit Skywalker Ranch. Howard and Bernadette explore his mother's crawl space." },
    { ep: 20, title: "The Fortification Implementation", date: "Apr 9, 2015", rating: 8.1, desc: "Sheldon and Amy build a blanket fort. Howard meets his half-brother Josh." },
    { ep: 21, title: "The Communication Deterioration", date: "Apr 16, 2015", rating: 8.0, desc: "The guys compete to write a message to alien civilizations for a NASA project." },
    { ep: 22, title: "The Graduation Transmission", date: "Apr 23, 2015", rating: 8.1, desc: "Leonard gives a commencement speech via video. Howard's drone project takes off." },
    { ep: 23, title: "The Maternal Combustion", date: "Apr 30, 2015", rating: 8.3, desc: "Leonard's and Sheldon's mothers meet and immediately clash over religion vs. science." },
    { ep: 24, title: "The Commitment Determination", date: "May 7, 2015", rating: 8.8, desc: "Sheldon decides to propose to Amy — but she calls to break up. Leonard and Penny elope to Las Vegas.", trivia: "Devastating cliffhanger: Sheldon is holding an engagement ring when Amy breaks up with him." }
  ],
  9: [
    { ep: 1, title: "The Matrimonial Momentum", date: "Sep 21, 2015", rating: 8.2, desc: "Leonard and Penny get married in Las Vegas but the celebration is dampened by a confession from Leonard." },
    { ep: 2, title: "The Separation Oscillation", date: "Sep 28, 2015", rating: 8.0, desc: "Leonard tries to make things right with Penny after the wedding. Sheldon creates a new Fun With Flags show." },
    { ep: 3, title: "The Bachelor Party Corrosion", date: "Oct 5, 2015", rating: 8.0, desc: "The guys take a road trip in a barely-working VW van for Leonard's belated bachelor party." },
    { ep: 4, title: "The 2003 Approximation", date: "Oct 12, 2015", rating: 8.0, desc: "Sheldon tries to revert to his 2003 lifestyle when Leonard moves in with Penny." },
    { ep: 5, title: "The Perspiration Implementation", date: "Oct 19, 2015", rating: 8.0, desc: "The guys take a fencing class. Raj and Stuart compete for the same woman." },
    { ep: 6, title: "The Helium Insufficiency", date: "Oct 26, 2015", rating: 7.9, desc: "Sheldon and Leonard try to buy black market helium for their experiment." },
    { ep: 7, title: "The Spock Resonance", date: "Nov 5, 2015", rating: 8.4, desc: "A documentary crew films Sheldon for a Spock documentary. Sheldon reveals he was going to propose to Amy.", trivia: "The revelation about the engagement ring is heartbreaking and beautiful." },
    { ep: 8, title: "The Mystery Date Observation", date: "Nov 12, 2015", rating: 8.0, desc: "Sheldon and the guys spy on Amy's date with another man. Bernadette reveals she's not pregnant." },
    { ep: 9, title: "The Platonic Permutation", date: "Nov 19, 2015", rating: 8.2, desc: "Sheldon and Amy spend Thanksgiving together as friends. Howard volunteers at a soup kitchen." },
    { ep: 10, title: "The Earworm Reverberation", date: "Dec 10, 2015", rating: 8.7, desc: "Sheldon can't get a song out of his head, which leads him to realize his true feelings for Amy. They reconcile.", trivia: "Sheldon shows up at Amy's door saying 'I love you' — a goosebump-inducing reconciliation scene." },
    { ep: 11, title: "The Opening Night Excitation", date: "Dec 17, 2015", rating: 8.9, desc: "Sheldon chooses to be with Amy on her birthday instead of seeing Star Wars: The Force Awakens. They consummate their relationship.", trivia: "A landmark episode: Sheldon and Amy finally sleep together. Professor Proton appears as Obi-Wan's ghost." },
    { ep: 12, title: "The Sales Call Sublimation", date: "Jan 7, 2016", rating: 8.0, desc: "Leonard helps Penny make a sales call at the university. Raj discovers something unusual about his office computer." },
    { ep: 13, title: "The Empathy Optimization", date: "Jan 14, 2016", rating: 8.0, desc: "The group is upset with Sheldon's behavior while sick. They exclude him from a trip to Las Vegas." },
    { ep: 14, title: "The Meemaw Materialization", date: "Feb 4, 2016", rating: 8.3, desc: "Sheldon's Meemaw visits and doesn't approve of Amy. She confronts Amy about breaking Sheldon's heart." },
    { ep: 15, title: "The Valentino Submergence", date: "Feb 11, 2016", rating: 8.0, desc: "Sheldon and Amy host a live Valentine's Day episode of Fun With Flags." },
    { ep: 16, title: "The Positive Negative Reaction", date: "Feb 18, 2016", rating: 8.4, desc: "Bernadette reveals she's pregnant. Howard is shocked but the group celebrates.", trivia: "The group's reaction to Bernadette's pregnancy, especially Howard's panic, is hilarious and touching." },
    { ep: 17, title: "The Celebration Experimentation", date: "Feb 25, 2016", rating: 8.3, desc: "The gang throws Sheldon his first ever birthday party. He's overwhelmed by emotions." },
    { ep: 18, title: "The Application Deterioration", date: "Mar 10, 2016", rating: 8.0, desc: "Sheldon, Leonard, and Howard file a patent with the help of a lawyer." },
    { ep: 19, title: "The Solder Excitation Diversion", date: "Mar 31, 2016", rating: 8.0, desc: "The girls discover Raj's strange secret. The guys build a prototype guidance system." },
    { ep: 20, title: "The Big Bear Precipitation", date: "Apr 7, 2016", rating: 8.0, desc: "The gang goes to a cabin in the woods. Raj is caught between two women." },
    { ep: 21, title: "The Viewing Party Combustion", date: "Apr 14, 2016", rating: 8.0, desc: "The gang argues about where to watch Game of Thrones. Stuart makes a play for Raj's ex." },
    { ep: 22, title: "The Fermentation Bifurcation", date: "Apr 28, 2016", rating: 8.0, desc: "The group goes wine tasting. Sheldon, Bernadette, and Raj stay behind and hang out with Zack." },
    { ep: 23, title: "The Line Substitution Solution", date: "May 5, 2016", rating: 8.1, desc: "Sheldon hires Stuart to wait in line for him. Penny and Leonard have a second wedding ceremony." },
    { ep: 24, title: "The Convergence Convergence", date: "May 12, 2016", rating: 8.4, desc: "Leonard and Penny have a wedding redo with family. Leonard's parents and Sheldon's mother have an unexpected interaction.", trivia: "Alfred and Mary Cooper's chemistry sets up Young Sheldon storylines." }
  ],
  10: [
    { ep: 1, title: "The Conjugal Conjecture", date: "Sep 19, 2016", rating: 8.1, desc: "Leonard and Penny's second wedding ceremony brings drama as their families clash." },
    { ep: 2, title: "The Military Miniaturization", date: "Sep 26, 2016", rating: 7.9, desc: "The Air Force is interested in Howard's guidance system. Penny is nervous about her upcoming work presentation." },
    { ep: 3, title: "The Dependence Transcendence", date: "Oct 3, 2016", rating: 7.9, desc: "The guys pull an all-nighter to finish the guidance system project. Raj and Bernadette go to a party." },
    { ep: 4, title: "The Cohabitation Experimentation", date: "Oct 10, 2016", rating: 8.3, desc: "Sheldon and Amy move in together as a five-week experiment when Amy's apartment floods.", trivia: "The beginning of Sheldon and Amy living together — a huge step for Sheldon." },
    { ep: 5, title: "The Hot Tub Contamination", date: "Oct 17, 2016", rating: 8.2, desc: "Sheldon and Amy work out their cohabitation issues. Howard and Bernadette deal with Stuart still living with them." },
    { ep: 6, title: "The Fetal Kick Catalyst", date: "Oct 24, 2016", rating: 8.0, desc: "Bernadette starts to feel the baby kick. Penny sells her car and Leonard buys it back." },
    { ep: 7, title: "The Veracity Elasticity", date: "Nov 3, 2016", rating: 8.1, desc: "Amy has been secretly living with Sheldon while pretending her apartment is being repaired." },
    { ep: 8, title: "The Brain Bowl Incubation", date: "Nov 10, 2016", rating: 8.0, desc: "Sheldon becomes obsessed with the idea that he and Amy should have a baby after growing a brain cell." },
    { ep: 9, title: "The Geology Elevation", date: "Nov 17, 2016", rating: 8.0, desc: "Sheldon is jealous when Bert wins a grant. A famous actor is interested in playing Raj's character for a movie." },
    { ep: 10, title: "The Property Division Collision", date: "Dec 1, 2016", rating: 8.1, desc: "Sheldon and Leonard argue about dividing their apartment belongings. Raj gets a dog named Cinnamon a playmate." },
    { ep: 11, title: "The Birthday Synchronicity", date: "Dec 15, 2016", rating: 8.5, desc: "Bernadette goes into labor. Howard and Bernadette welcome their daughter Halley.", trivia: "Baby Halley is born on the same night as the birth of Sheldon's genius theory." },
    { ep: 12, title: "The Holiday Summation", date: "Jan 5, 2017", rating: 8.1, desc: "The gang recaps their holiday adventures. Sheldon and Amy adjust to living together." },
    { ep: 13, title: "The Romance Recalibration", date: "Jan 19, 2017", rating: 8.0, desc: "Penny asks Leonard to be more romantic. Sheldon complains about changes in the apartment." },
    { ep: 14, title: "The Emotion Detection Automation", date: "Feb 2, 2017", rating: 8.0, desc: "Raj gets an emotion-detecting program. Sheldon goes on a college interview." },
    { ep: 15, title: "The Locomotion Reverberation", date: "Feb 9, 2017", rating: 8.0, desc: "Sheldon works on a small version of the guidance system. Leonard and Howard deal with the military." },
    { ep: 16, title: "The Allowance Evaporation", date: "Feb 16, 2017", rating: 8.0, desc: "Raj's father cuts him off financially. Sheldon and Amy deal with a couple vlogging about their relationship." },
    { ep: 17, title: "The Comic-Con Conundrum", date: "Feb 23, 2017", rating: 8.0, desc: "Raj can't afford Comic-Con. Sheldon tries to get Amy interested in going." },
    { ep: 18, title: "The Escape Hatch Identification", date: "Mar 9, 2017", rating: 8.1, desc: "Raj moves into Sheldon's old room. The group analyzes why everyone keeps running from their problems." },
    { ep: 19, title: "The Collaboration Fluctuation", date: "Mar 16, 2017", rating: 8.0, desc: "Sheldon and Amy work together on a neuroscience-physics project. Raj and Howard join a band." },
    { ep: 20, title: "The Recollection Dissipation", date: "Mar 30, 2017", rating: 8.0, desc: "Sheldon can't remember what he did on a day he lost track of. The others pitch in at Bernadette's work." },
    { ep: 21, title: "The Separation Agitation", date: "Apr 6, 2017", rating: 8.0, desc: "Howard and Bernadette struggle with leaving baby Halley at daycare." },
    { ep: 22, title: "The Cognition Regeneration", date: "Apr 27, 2017", rating: 8.0, desc: "Penny's ex Zack asks her out to lunch, making Leonard uncomfortable." },
    { ep: 23, title: "The Gyroscopic Collapse", date: "May 4, 2017", rating: 8.1, desc: "The military takes the guys' guidance system project. Amy is offered a fellowship at Princeton." },
    { ep: 24, title: "The Long Distance Dissonance", date: "May 11, 2017", rating: 8.6, desc: "Ramona Nowitzki returns and flirts with Sheldon while Amy is at Princeton. Sheldon flies to Princeton and proposes to Amy.", trivia: "Sheldon's surprise proposal at Amy's Princeton office is one of the most surprising and romantic moments." }
  ],
  11: [
    { ep: 1, title: "The Proposal Proposal", date: "Sep 25, 2017", rating: 8.5, desc: "Amy says yes to Sheldon's proposal. Raj has relationship complications." },
    { ep: 2, title: "The Retraction Reaction", date: "Oct 2, 2017", rating: 8.0, desc: "Leonard makes controversial comments about physics on the radio. Bernadette and Penny deal with work issues." },
    { ep: 3, title: "The Relaxation Integration", date: "Oct 9, 2017", rating: 8.0, desc: "Sheldon struggles to relax about wedding planning. Raj dates two women simultaneously." },
    { ep: 4, title: "The Explosion Implosion", date: "Oct 16, 2017", rating: 8.2, desc: "Howard bonds with his daughter by building a model rocket. Sheldon and Amy fight over their wedding." },
    { ep: 5, title: "The Collaboration Contamination", date: "Oct 23, 2017", rating: 8.0, desc: "Amy works with Howard in the lab, making Sheldon jealous." },
    { ep: 6, title: "The Proton Regeneration", date: "Nov 2, 2017", rating: 8.1, desc: "Sheldon competes with Wil Wheaton for the role of Professor Proton in a new kids' show." },
    { ep: 7, title: "The Geology Methodology", date: "Nov 9, 2017", rating: 8.0, desc: "Sheldon secretly works with Bert on a geological project. Howard gets career advice." },
    { ep: 8, title: "The Tesla Recoil", date: "Nov 16, 2017", rating: 8.1, desc: "The military steals the guys' idea. Howard is upset when his old NASA buddy undermines him." },
    { ep: 9, title: "The Bitcoin Entanglement", date: "Nov 30, 2017", rating: 8.4, desc: "The guys try to recover Bitcoin they mined years ago that's now worth thousands.", trivia: "A perfectly timed episode given the Bitcoin craze of 2017." },
    { ep: 10, title: "The Confidence Erosion", date: "Dec 7, 2017", rating: 8.0, desc: "Raj realizes his love life problems stem from his controlling nature. Sheldon offends Amy about her research." },
    { ep: 11, title: "The Celebration Reverberation", date: "Dec 14, 2017", rating: 8.1, desc: "Sheldon and Amy plan their wedding. Howard and Bernadette deal with Halley being sick on her birthday." },
    { ep: 12, title: "The Matrimonial Metric", date: "Jan 4, 2018", rating: 8.1, desc: "Sheldon and Amy test their friends to determine who should be in their wedding party." },
    { ep: 13, title: "The Solo Oscillation", date: "Jan 11, 2018", rating: 8.0, desc: "Sheldon kicks Amy out for a night so he can work alone. Raj performs at open mic night." },
    { ep: 14, title: "The Separation Triangulation", date: "Jan 18, 2018", rating: 8.0, desc: "Raj is caught between his ex and his new girlfriend. Sheldon and Amy compete with another couple." },
    { ep: 15, title: "The Novelization Correlation", date: "Feb 1, 2018", rating: 8.0, desc: "Sheldon writes a novel featuring a character suspiciously similar to Amy." },
    { ep: 16, title: "The Neonatal Nomenclature", date: "Mar 1, 2018", rating: 8.2, desc: "Howard and Bernadette argue about naming their second baby. Sheldon talks to his mother about the wedding." },
    { ep: 17, title: "The Athenaeum Allocation", date: "Mar 8, 2018", rating: 8.1, desc: "Sheldon and Amy search for a wedding venue. Leonard discovers his name was on a paper he didn't contribute to." },
    { ep: 18, title: "The Gates Excitation", date: "Mar 29, 2018", rating: 8.2, desc: "Penny meets Bill Gates through work and the guys desperately try to meet him too." },
    { ep: 19, title: "The Tenant Disassociation", date: "Apr 5, 2018", rating: 8.0, desc: "Leonard runs for president of the tenants' association. Amy and Howard fight over Sheldon." },
    { ep: 20, title: "The Reclusive Potential", date: "Apr 12, 2018", rating: 8.1, desc: "The guys visit a reclusive scientist. The girls host Amy's bachelorette party." },
    { ep: 21, title: "The Comet Polarization", date: "Apr 19, 2018", rating: 8.0, desc: "Raj discovers a comet. Stuart becomes Denise the comic store employee's boyfriend." },
    { ep: 22, title: "The Monetary Insufficiency", date: "Apr 26, 2018", rating: 8.1, desc: "The girls help Amy find a wedding dress. Sheldon and the guys learn about crypto." },
    { ep: 23, title: "The Sibling Realignment", date: "May 3, 2018", rating: 8.3, desc: "Sheldon and Leonard go to Texas to convince Georgie to come to the wedding." },
    { ep: 24, title: "The Bow Tie Asymmetry", date: "May 10, 2018", rating: 9.1, desc: "Sheldon and Amy get married! Mark Hamill officiates. Sheldon and Amy realize their work together could lead to a Nobel Prize.", trivia: "The wedding of the decade! Mark Hamill as the officiant. Kathy Bates and Teller appear. 18.5 million viewers watched." }
  ],
  12: [
    { ep: 1, title: "The Conjugal Configuration", date: "Sep 24, 2018", rating: 8.1, desc: "Sheldon and Amy return from their honeymoon. Penny and Leonard deal with their Nobel Prize project." },
    { ep: 2, title: "The Wedding Gift Wormhole", date: "Oct 1, 2018", rating: 8.0, desc: "Sheldon and Amy try to solve the puzzle of Leonard and Penny's wedding gift." },
    { ep: 3, title: "The Procreation Calculation", date: "Oct 8, 2018", rating: 8.0, desc: "The group discusses having children. Raj contemplates an arranged marriage." },
    { ep: 4, title: "The Tam Turbulence", date: "Oct 15, 2018", rating: 8.1, desc: "Sheldon's childhood friend Tam from East Texas shows up, and Sheldon is furious with him." },
    { ep: 5, title: "The Planetarium Collision", date: "Oct 22, 2018", rating: 8.0, desc: "Amy and Raj work together on a planetarium show. Howard and Bernadette try new parenting techniques." },
    { ep: 6, title: "The Implication Realization", date: "Nov 1, 2018", rating: 8.0, desc: "Sheldon and Amy's research starts attracting attention. Raj and Anu go on their first date." },
    { ep: 7, title: "The Grant Allocation Derivation", date: "Nov 8, 2018", rating: 8.0, desc: "Leonard must decide how to distribute a research grant. Penny and Bernadette compete at work." },
    { ep: 8, title: "The Consummation Deviation", date: "Nov 15, 2018", rating: 8.0, desc: "Raj and Anu consider sleeping together. Sheldon is thrilled when his famous idol visits." },
    { ep: 9, title: "The Citation Negation", date: "Nov 29, 2018", rating: 8.0, desc: "A Russian paper threatens to disprove Sheldon and Amy's super-asymmetry theory." },
    { ep: 10, title: "The VCR Illumination", date: "Dec 6, 2018", rating: 8.2, desc: "Sheldon finds a childhood video of himself that provides unexpected motivation." },
    { ep: 11, title: "The Paintball Scattering", date: "Jan 3, 2019", rating: 8.1, desc: "The gang plays paintball and old rivalries surface. Raj and Anu move their relationship forward." },
    { ep: 12, title: "The Propagation Proposition", date: "Jan 10, 2019", rating: 8.0, desc: "Penny's ex Zack asks Leonard and Penny for a huge favor. Raj questions his relationship with Anu." },
    { ep: 13, title: "The Confirmation Polarization", date: "Jan 17, 2019", rating: 8.2, desc: "Two physicists from Chicago confirm super-asymmetry, but want to share credit." },
    { ep: 14, title: "The Meteorite Manifestation", date: "Jan 31, 2019", rating: 8.0, desc: "Bert's meteorite is stolen. Howard and Bernadette fight about their backyard playhouse." },
    { ep: 15, title: "The Donation Oscillation", date: "Feb 7, 2019", rating: 8.0, desc: "Leonard decides whether to donate sperm to Zack. Raj starts a doggy playdate business." },
    { ep: 16, title: "The D&D Vortex", date: "Feb 21, 2019", rating: 8.3, desc: "The gang plays Dungeons & Dragons with William Shatner, Joe Manganiello, Kareem Abdul-Jabbar, and Kevin Smith.", trivia: "An epic celebrity D&D game that fans loved." },
    { ep: 17, title: "The Conference Valuation", date: "Mar 7, 2019", rating: 8.0, desc: "Penny and Bernadette attend a conference. Sheldon and Amy's Nobel competition heats up." },
    { ep: 18, title: "The Laureate Accumulation", date: "Apr 4, 2019", rating: 8.1, desc: "Sheldon and Amy are attacked by rival Nobel candidates. Howard and Bernadette babysit Halley and Neil." },
    { ep: 19, title: "The Inspiration Deprivation", date: "Apr 11, 2019", rating: 8.0, desc: "Amy worries she's let Sheldon control their work life. Raj and Howard babysit." },
    { ep: 20, title: "The Decision Reverberation", date: "Apr 18, 2019", rating: 8.0, desc: "Leonard is assertive at work. Raj questions his purpose." },
    { ep: 21, title: "The Plagiarism Schism", date: "Apr 25, 2019", rating: 8.0, desc: "Pemberton plagiarizes a paper, jeopardizing the Nobel race." },
    { ep: 22, title: "The Maternal Conclusion", date: "May 2, 2019", rating: 8.3, desc: "Leonard's mother finally shows him affection. Raj considers moving to London." },
    { ep: 23, title: "The Change Constant", date: "May 16, 2019", rating: 9.0, desc: "Sheldon and Amy WIN THE NOBEL PRIZE! Sheldon struggles with fame. Penny helps Sheldon adapt to change.", trivia: "First half of the series finale. Sheldon and Amy's Nobel win is triumphant." },
    { ep: 24, title: "The Stockholm Syndrome", date: "May 16, 2019", rating: 9.3, desc: "The gang travels to Stockholm for the Nobel ceremony. Sheldon gives a heartfelt speech thanking his friends, finally showing his growth as a person. Penny reveals she's pregnant.", trivia: "The series finale. 18 million viewers. Sheldon's speech thanking each of his friends is one of the most emotional moments in TV history. The elevator finally works." }
  ]
};

// ── FUN FACTS & BEHIND THE SCENES ──
const FUN_FACTS = [
  {
    category: "Origins",
    icon: "🎬",
    facts: [
      { title: "The Original Pilot Was Very Different", text: "The unaired pilot featured a completely different female lead named Katie (played by Amanda Walsh) and a character named Gilda. CBS asked for a retool, leading to the creation of Penny and the removal of Katie." },
      { title: "Chuck Lorre's Inspiration", text: "Chuck Lorre was inspired to create the show after meeting a group of computer programmers and noticing how their brilliant minds clashed with their social skills." },
      { title: "Bill Prady's Tech Background", text: "Co-creator Bill Prady actually worked as a computer programmer before entering television, giving him authentic insight into geek culture." },
      { title: "The Theme Song Auditions", text: "The Barenaked Ladies weren't the first choice for the theme song. The producers auditioned several bands before the Barenaked Ladies nailed the catchy 'History of Everything.'" },
      { title: "Jim Parsons Almost Didn't Get Cast", text: "Jim Parsons auditioned for Sheldon three times before getting the part. The producers initially weren't sure he was right for the role." }
    ]
  },
  {
    category: "Science & Accuracy",
    icon: "🔬",
    facts: [
      { title: "Real Science Consultant", text: "UCLA professor David Saltzberg reviewed every script and wrote the equations on the whiteboards. All the science discussed and shown on the show is actually real and accurate." },
      { title: "The Whiteboards Are Real", text: "Every equation shown on the whiteboards in Leonard and Sheldon's apartment was scientifically accurate and often related to current research topics." },
      { title: "Mayim Bialik Is a Real Neuroscientist", text: "Mayim Bialik, who plays neurobiologist Amy Farrah Fowler, actually holds a Ph.D. in neuroscience from UCLA." },
      { title: "Sheldon's IQ", text: "Sheldon's IQ of 187 would make him smarter than Albert Einstein (estimated 160-190) and Stephen Hawking (160)." },
      { title: "Real Scientific Papers", text: "Several scientific papers referenced in the show are real publications, and the research topics discussed are based on actual ongoing research at institutions like Caltech." }
    ]
  },
  {
    category: "Set & Production",
    icon: "🏠",
    facts: [
      { title: "The Elevator Has Always Been Broken", text: "The elevator in the apartment building has never worked throughout the entire series — until the very last episode. The flashback episode 'The Staircase Implementation' reveals it broke when Leonard's rocket fuel experiment went wrong." },
      { title: "Apartment 4A Is on Stage 25", text: "The show was filmed on Stage 25 at Warner Bros. Studios in Burbank, California — the same stage where Friends was filmed." },
      { title: "The Apartment Changes", text: "The production design team gradually added more items to the apartment sets over the seasons, reflecting the characters' evolving lives and relationships." },
      { title: "Live Studio Audience", text: "The Big Bang Theory was filmed before a live studio audience, with tapings usually on Tuesday nights. Episodes took about 4-5 hours to film." },
      { title: "Penny's Last Name Mystery", text: "For 12 seasons, Penny's maiden name was never revealed. It became a running joke among writers and fans. When she married Leonard, she became Penny Hofstadter." },
      { title: "The Couch Spot", text: "Sheldon's spot on the couch (0° from the television at the optimal angle, with the air conditioning on his back in summer but not his head in winter) was so integral to the show that it essentially became a character itself." }
    ]
  },
  {
    category: "Records & Achievements",
    icon: "🏆",
    facts: [
      { title: "Highest-Paid TV Actors", text: "At their peak, Jim Parsons, Johnny Galecki, and Kaley Cuoco each earned $1 million per episode, making them among the highest-paid TV actors in history." },
      { title: "12-Season Run", text: "The Big Bang Theory ran for 12 seasons and 279 episodes, making it the longest-running multi-camera sitcom in TV history." },
      { title: "Emmy Dominance", text: "Jim Parsons won the Emmy for Outstanding Lead Actor in a Comedy Series four times (2010, 2011, 2013, 2014)." },
      { title: "Viewer Milestone", text: "The series finale was watched by 18 million viewers, making it the most-watched entertainment telecast of the 2018-2019 season." },
      { title: "Syndication Record", text: "The show's syndication deal with TBS was worth over $1.5 billion, one of the largest in television history." },
      { title: "Global Phenomenon", text: "The show has been broadcast in over 70 countries and dubbed in over 30 languages." }
    ]
  },
  {
    category: "Easter Eggs & Running Gags",
    icon: "🥚",
    facts: [
      { title: "73 Is the Best Number", text: "Sheldon declares that 73 is the best number because it's the 21st prime number, its mirror (37) is the 12th prime, and its mirror (21) is the product of 7 and 3. The 73rd episode is actually titled 'The Alien Parasite Hypothesis.'"},
      { title: "Knock Knock Knock, Penny!", text: "Sheldon's triple-knock ritual (knock-knock-knock, 'Penny!') originated from his childhood when he walked in on his parents in an intimate moment. He developed the habit to give people time to 'compose themselves.'" },
      { title: "Chuck Lorre's Vanity Cards", text: "Every episode ends with a unique 'vanity card' from Chuck Lorre, containing personal essays, jokes, or observations. There are over 600 of these." },
      { title: "Soft Kitty Origins", text: "'Soft Kitty' was adapted from a real children's song. The show had to pay royalties to the original composer's estate after a lawsuit." },
      { title: "The Number 73 Episode", text: "In an amazing mathematical coincidence, the show's 73rd episode is also the episode where Sheldon first states 73 is the best number." },
      { title: "Howard's Belt Buckles", text: "Howard's collection of oversized, themed belt buckles became a beloved character detail. The costume department created over 30 unique buckles throughout the series." }
    ]
  },
  {
    category: "Cast Chemistry & Behind the Scenes",
    icon: "❤️",
    facts: [
      { title: "Real-Life Friendship", text: "The main cast became genuine friends off-screen. They would have group dinners together before tapings and celebrated personal milestones together." },
      { title: "Kaley Cuoco and Johnny Galecki Dated", text: "Kaley Cuoco and Johnny Galecki secretly dated for two years during the early seasons of the show, mirroring their on-screen relationship." },
      { title: "Jim Parsons' Influence on Sheldon", text: "Many of Sheldon's mannerisms, including specific facial expressions and the way he delivers 'Bazinga,' were developed by Jim Parsons, not scripted." },
      { title: "Simon Helberg's Real Musical Talent", text: "Simon Helberg is actually an accomplished pianist in real life. His piano playing in the show is real, not dubbed." },
      { title: "The Cast Took Pay Cuts", text: "In a show of solidarity, the five original cast members took pay cuts so that Mayim Bialik and Melissa Rauch could receive raises." },
      { title: "Jim Parsons Ended the Show", text: "The show ended after Season 12 primarily because Jim Parsons decided to leave. The producers felt they couldn't continue without Sheldon." }
    ]
  },
  {
    category: "Cultural Impact",
    icon: "🌍",
    facts: [
      { title: "Popularized Geek Culture", text: "The show is credited with helping bring nerd and geek culture into the mainstream, making it 'cool' to be interested in science, comics, and gaming." },
      { title: "Real Asteroid Named", text: "Asteroid 246247 was named 'Amyfarrahfowler' in honor of the character, and another asteroid was named 'Bazinga' in 2013." },
      { title: "Soft Kitty Merchandise", text: "'Soft Kitty' became such a cultural phenomenon that it spawned its own line of merchandise, including t-shirts, mugs, and even a singing plush toy." },
      { title: "Rock Paper Scissors Lizard Spock", text: "The game invented for the show became so popular that it's now commonly played in real life and has been featured in other media." },
      { title: "Inspired Real Scientists", text: "Multiple scientists have credited The Big Bang Theory with inspiring them to pursue careers in physics, engineering, and other STEM fields." },
      { title: "Roommate Agreements Are Real Now", text: "The concept of a formal roommate agreement, popularized by Sheldon, has actually been adopted by many real-life roommates and some universities." }
    ]
  }
];

// ── EMOTIONAL MOMENTS (with YouTube embeds) ──
const MOMENTS = [
  {
    id: "sheldon-nobel-speech",
    title: "Sheldon's Nobel Prize Speech",
    description: "In the series finale, Sheldon wins the Nobel Prize and gives a heartfelt speech acknowledging that his friends are his greatest achievement. He thanks each one by name, showing how much he's grown.",
    category: "emotional",
    season: 12,
    episode: 24,
    youtubeId: "P4_Xk5rMNPo",
    quote: "I have been encouraged, sustained, and inspired by my remarkable friends. I truly am the luckiest man alive."
  },
  {
    id: "howard-bernadette-song",
    title: "Howard Sings 'If I Didn't Have You' for Bernadette",
    description: "While Bernadette is in quarantine at the hospital, Howard performs a heartfelt original song for her through the glass. Simon Helberg's real musical talent shines in this genuinely romantic scene.",
    category: "romantic",
    season: 7,
    episode: 6,
    youtubeId: "GEKhqUJd3yY",
    quote: "If I didn't have you, life would be dreary... I'd be string theory without any string."
  },
  {
    id: "sheldon-amy-first-kiss",
    title: "Sheldon and Amy's First Real Kiss",
    description: "On a Valentine's Day train ride, Sheldon spontaneously kisses Amy — a genuine, romantic kiss that marks a turning point in their relationship.",
    category: "romantic",
    season: 7,
    episode: 15,
    youtubeId: "7Tl5VNxxbKg",
    quote: "That was nice."
  },
  {
    id: "bath-item-gift",
    title: "The Christmas Napkin — Sheldon Hugs Penny",
    description: "When Penny gives Sheldon a napkin signed by Leonard Nimoy (with DNA!), Sheldon is so overwhelmed that he gives her all his gift baskets and a rare, genuine hug.",
    category: "heartwarming",
    season: 2,
    episode: 11,
    youtubeId: "jjBgMXBHtss",
    quote: "I possess the DNA of Leonard Nimoy?! Do you realize what this means?... I have to give you a gift equal to this... I know what to do!"
  },
  {
    id: "soft-kitty-first",
    title: "The First Time They Sing 'Soft Kitty'",
    description: "When Sheldon is sick, Penny reluctantly sings him 'Soft Kitty, Warm Kitty' — beginning one of the most beloved recurring bits in sitcom history.",
    category: "heartwarming",
    season: 1,
    episode: 11,
    youtubeId: "XqWOfFljCIs",
    quote: "Soft kitty, warm kitty, little ball of fur... Happy kitty, sleepy kitty, purr purr purr."
  },
  {
    id: "elevator-fixed",
    title: "The Elevator Finally Works",
    description: "In the series finale, after 12 seasons of being broken, the elevator finally gets fixed. Leonard and Penny ride it together — a perfect metaphor for how far everyone has come.",
    category: "iconic",
    season: 12,
    episode: 24,
    youtubeId: "M1j6rOCiSFc",
    quote: "The elevator's working!"
  },
  {
    id: "sheldon-says-i-love-you",
    title: "Sheldon Tells Amy He Loves Her",
    description: "During a prom night on the building's rooftop, Sheldon panics — then sincerely tells Amy 'I love you' for the very first time. Jim Parsons delivers it with perfect vulnerability.",
    category: "romantic",
    season: 8,
    episode: 8,
    youtubeId: "Y7PP_w0P2sQ",
    quote: "Amy... there's something I need to tell you... I love you."
  },
  {
    id: "howard-space-launch",
    title: "Howard Launches Into Space",
    description: "Howard fulfills his dream of going to space aboard a Russian Soyuz rocket. He marries Bernadette via video feed while in orbit — one of the most spectacular TV moments ever.",
    category: "iconic",
    season: 5,
    episode: 24,
    youtubeId: "yxKkZF7TydI",
    quote: "Howard Joel Wolowitz, do you take Bernadette Maryann Rostenkowski to be your wife? ...I do."
  },
  {
    id: "penny-leonard-proposal",
    title: "Leonard Proposes to Penny",
    description: "After years of an on-again, off-again relationship, Leonard proposes to Penny, and she finally says yes. A beautiful culmination of their seven-year journey.",
    category: "romantic",
    season: 7,
    episode: 23,
    youtubeId: "8MLQ0VYuXBU",
    quote: "Will you marry me? — Yes!"
  },
  {
    id: "professor-proton-death",
    title: "Professor Proton's Farewell",
    description: "After Professor Proton (Arthur Jeffries) passes away, he appears to Sheldon as a Force ghost on Star Wars Day. Their emotional goodbye shows Sheldon's deeply hidden vulnerable side.",
    category: "emotional",
    season: 7,
    episode: 22,
    youtubeId: "KHJB3B5VGcA",
    quote: "You know, Sheldon, I may not have been the greatest scientist, but I inspired you. And you're going to inspire millions."
  },
  {
    id: "howard-letter-from-dad",
    title: "Howard's Letter From His Father",
    description: "When Howard finds an unopened letter from his estranged father, each friend tells him a different version of what the letter says — so he'll never know which is real, but all are beautiful.",
    category: "emotional",
    season: 6,
    episode: 19,
    youtubeId: "TW7CRbJ3b0Q",
    quote: "I was just a kid when you left. Why did you never come back?"
  },
  {
    id: "sheldon-proposal",
    title: "Sheldon Proposes to Amy",
    description: "In a jaw-dropping season finale, Sheldon flies to Princeton and surprises Amy with a proposal. After carrying the ring for over a year, Sheldon gets down on one knee.",
    category: "romantic",
    season: 10,
    episode: 24,
    youtubeId: "pJZ-bP5HKXE",
    quote: "Amy Farrah Fowler, will you marry me?"
  },
  {
    id: "bazinga-origin",
    title: "The First 'Bazinga!'",
    description: "Sheldon delivers his first 'Bazinga!' in Season 2, and a catchphrase legend is born. It would go on to become one of the most recognizable catchphrases in television history.",
    category: "funny",
    season: 2,
    episode: 1,
    youtubeId: "obKLdDhayfI",
    quote: "Bazinga!"
  },
  {
    id: "staircase-implementation",
    title: "How the Elevator Broke",
    description: "The flashback episode revealing how Leonard's rocket fuel experiment caused the elevator to break — and how Sheldon saved Leonard's life, cementing their friendship forever.",
    category: "iconic",
    season: 3,
    episode: 22,
    youtubeId: "2PoiqKuESjM",
    quote: "Quick! Get in! Get in! Get in!"
  },
  {
    id: "sheldon-amy-wedding",
    title: "Sheldon and Amy's Wedding",
    description: "The wedding of the century: Sheldon and Amy tie the knot with Mark Hamill as the officiant. Kathy Bates and Teller guest star. A perfect celebration of love.",
    category: "emotional",
    season: 11,
    episode: 24,
    youtubeId: "IvFGmR-DwTs",
    quote: "Amy, I usually don't have much use for feelings, and I'd cross the street to avoid them, but right now I have so many, I could explode."
  },
  {
    id: "raj-talks-to-women",
    title: "Raj Finally Talks to Women (Sober)",
    description: "After six seasons of being unable to speak to women without alcohol, Raj finally breaks through his selective mutism. A genuinely triumphant character moment.",
    category: "iconic",
    season: 6,
    episode: 24,
    youtubeId: "vQfKE-bSXhI",
    quote: "Hello. I'm Rajesh Koothrappali. And I can talk to you."
  }
];

// ── ICONIC QUOTES ──
const QUOTES = [
  { text: "Bazinga!", author: "Sheldon Cooper", season: 2 },
  { text: "I'm not crazy. My mother had me tested.", author: "Sheldon Cooper", season: 4 },
  { text: "Soft kitty, warm kitty, little ball of fur. Happy kitty, sleepy kitty, purr purr purr.", author: "Sheldon & Penny", season: 1 },
  { text: "People are idiots, Leonard.", author: "Sheldon Cooper", season: 3 },
  { text: "I cry because others are stupid and it makes me sad.", author: "Sheldon Cooper", season: 3 },
  { text: "Under no circumstances are you to touch the thermostat.", author: "Sheldon Cooper", season: 1 },
  { text: "It's not a tiara, it's a diadem.", author: "Amy Farrah Fowler", season: 5 },
  { text: "I'm the king of the nerds!", author: "Howard Wolowitz", season: 2 },
  { text: "You know what'd be a great invention? Jeans that don't leave marks on your thighs.", author: "Penny", season: 4 },
  { text: "I'm Dr. Sheldon Cooper. Welcome to 'Fun With Flags.'", author: "Sheldon Cooper", season: 5 },
  { text: "Live long and prosper.", author: "Sheldon Cooper (quoting Spock)", season: 1 },
  { text: "Engineering is merely the slow younger brother of physics.", author: "Sheldon Cooper", season: 4 },
  { text: "If I could, I'd take back 'I love you.'", author: "Sheldon Cooper (to Amy)", season: 9 },
  { text: "Scissors cuts paper, paper covers rock, rock crushes lizard, lizard poisons Spock, Spock smashes scissors, scissors decapitates lizard, lizard eats paper, paper disproves Spock, Spock vaporizes rock, and as it always has, rock crushes scissors.", author: "Sheldon Cooper", season: 2 },
  { text: "I have been encouraged, sustained, and inspired by my remarkable friends.", author: "Sheldon Cooper (Nobel Speech)", season: 12 }
];
